-- vim.diagnostic.config({
--   virtual_text = {
--     enabled = true,
--   },
--   virtual_lines = {
--     enabled = true,
--   },
--
--   signs = true,
--   underline = false,
--   update_in_insert = true,
--   severity_sort = true,
--   current_line = false,
-- })
